# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JtoD.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import jtod

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 30, 471, 391))
        self.widget.setObjectName("widget")

        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(70, 20, 301, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.filename_input = QtWidgets.QLineEdit(self.frame)
        self.filename_input.setGeometry(QtCore.QRect(20, 220, 251, 21))
        self.filename_input.setObjectName("filename_input")
        
        self.Enter_button = QtWidgets.QPushButton(self.frame)
        self.Enter_button.setGeometry(QtCore.QRect(190, 270, 89, 25))
        self.Enter_button.setMouseTracking(True)
        self.Enter_button.setTabletTracking(True)
        self.Enter_button.setObjectName("Enter_button")
        self.Enter_button.clicked.connect(self.convert_file)
        
        self.minor_text = QtWidgets.QLabel(self.frame)
        self.minor_text.setGeometry(QtCore.QRect(90, 170, 121, 41))
        self.minor_text.setObjectName("minor_text")
        
        self.main_text = QtWidgets.QLabel(self.frame)
        self.main_text.setGeometry(QtCore.QRect(40, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.main_text.setFont(font)
        self.main_text.setObjectName("main_text")
        
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(150, 360, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 22))
        self.menubar.setWhatsThis("")
        self.menubar.setProperty("menubar", "")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filename_input.setText(_translate("MainWindow", ""))
        self.Enter_button.setText(_translate("MainWindow", "Enter"))
        self.minor_text.setText(_translate("MainWindow", "Type name of file"))
        self.main_text.setText(_translate("MainWindow", "JSON To Docx Converter"))
        self.progressBar.setObjectName("progressBar")

    def convert_file(self):
        filename = self.filename_input.text()
        # Remove any mistake in spacing
        filename = filename.strip() #replace(" ", "")

        if not filename.endswith(".json"):
            QtWidgets.QMessageBox.warning(self.centralwidget, "File not allowed", "File must have a .json extension")
            return
        
        try:
            jtod.convert_json_to_docx(filename)
        except FileNotFoundError:
            QtWidgets.QMessageBox.warning(self.centralwidget, "File not found", "File not found")
            return
        
        # Create a new widget to display the "Done" message, progress bar and back button
        self.done_widget = QtWidgets.QWidget(self.centralwidget)
        self.done_widget.setObjectName("done_widget")

        self.done_label = QtWidgets.QLabel(self.done_widget)
        self.done_label.setGeometry(QtCore.QRect(40, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.done_label.setFont(font)
        self.done_label.setObjectName("done_label")
        self.done_label.setText("Conversion Complete!")

        self.done_button = QtWidgets.QPushButton(self.done_widget)
        self.done_button.setGeometry(QtCore.QRect(190, 270, 89, 25))
        self.done_button.setMouseTracking(True)
        self.done_button.setTabletTracking(True)
        self.done_button.setObjectName("done_button")
        self.done_button.setText("Back")
        self.done_button.clicked.connect(self.show_front_page)
        
        self.progressBar.setParent(self.done_widget)
        self.progressBar.setGeometry(QtCore.QRect(150, 100, 118, 23))
        self.progressBar.setProperty("value", 100)

        self.widget.hide()
        self.done_widget.show()
    
    def show_front_page(self):
        # Hide the done widget and show the front page widget
        self.done_widget.hide()
        self.widget.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
